version: '3.4'

services:

  reader:
    build: ./api
    depends_on:
      - cassandra
    ports:
      - "8080:8080"
    command: ./reader -port=8080

  writer:
    build: ./api
    depends_on:
      - cassandra
    ports:
      - "8081:8081"
    command: ./writer -port=8081

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"